### PR TITLE
Add almost the perfect version of bob-walker

### PR DESCRIPTION
**Pull request by samjsharpe**
I'd already done all the hard work for this, so I implemented a brainf##k to
trollscript translator using sed and piped it the non-sport version of
bob-walker.fk (trollscript doesn't accept passing input).

```
curl https://raw.githubusercontent.com/dcarley/bob-walker/7cd16ef95cb0a0591b2bd1ec9a526025f042c20e/bob-walker.fk | sed -e 's/^/tro/g' -e 's/>/ooo/g' -e 's/</ool/g' -e 's/+/olo/g' -e 's/-/oll/g' -e 's/\./loo/g' -e 's/,/lol/g' -e 's/\[/llo/g' -e 's/\]/lll/g' -e 's/$/ll./g' > bob-walker.troll
```

You'd think the triviality of this port would stop me, but I'm submitting it as
an example of how versatile and adaptable bob-walker is.

### CODE REVIEW

**Comment by rjw1** [comment]
all the :eggplant: s

**Comment by philandstuff** [comment]
:whale:

**Comment by annashipman** [comment]
:egg:

**Comment by ajlanghorn** [comment]
:volcano:

**Comment by dcarley** [comment]
:trollface: :trollface: :trollface:

**Pull request merged**
